import re

CONFIG_PATH = 'CONFIG_PATH'
PRECISION = 'PRECISION'

OUTPUT = 'OUTPUT'
SOURCES = 'SOURCES'
DATA_SOURCE_TYPE = 'TYPE'
INPUT = 'INPUT'
MIMES = 'MIMES'
CHARACTER = 'CHARACTER'

ENV_DIR = 'ENV_DIR'
DATA_SOURCE_INSTANCE = 'DATA_SOURCE_INSTANCE'
TYPE_MNIST = 'MNIST'

FILE_NAME_TEMPLATE_CHARACTER_PARTIAL = 'CHAR'
FILE_NAME_TEMPLATE_VERSION_PARTIAL = 'VER'
FILE_NAME_TEMPLATE_EXTENSION_PARTIAL = "EXT"
FILE_NAME_TEMPLATE = '{0}_{1}'.format(
    FILE_NAME_TEMPLATE_CHARACTER_PARTIAL,
    FILE_NAME_TEMPLATE_VERSION_PARTIAL
)
FILE_EXTENSION = 'csv'
FILE_META_EXTRACTOR_PATTERN = "(?P<{0}>.*)_(?P<{1}>.*)\.(?P<{2}>.*)".format(
    FILE_NAME_TEMPLATE_CHARACTER_PARTIAL,
    FILE_NAME_TEMPLATE_VERSION_PARTIAL,
    FILE_NAME_TEMPLATE_EXTENSION_PARTIAL
)
FILE_META_EXTRACTOR_REGEX = re.compile(FILE_META_EXTRACTOR_PATTERN)

PCA_COMPONENTS = 'PCA_COMPONENTS'

MODEL_SAVE = 'SAVE'
MODEL_CONFIG = "MODEL"
MODEL_KERAS = 'KERAS'
MODEL_CLASS = 'MODEL_CLASS'
MODEL_TYPE = "TYPE"
