import re

CONFIG_PATH = 'CONFIG_PATH'
PRECISION = 'PRECISION'

OUTPUT = 'OUTPUT'
SOURCES = 'SOURCES'
DATA_SOURCE_TYPE = 'TYPE'
INPUT = 'INPUT'
MIMES = 'MIMES'
CHARACTER = 'CHARACTER'

ENV_DIR = 'ENV_DIR'
DATA_SOURCE_INSTANCE = 'DATA_SOURCE_INSTANCE'
TYPE_MNIST = 'MNIST'

FEATURE_FILE_EXTENSION = 'csv'

PCA_COMPONENTS = 'PCA_COMPONENTS'

MODEL_SAVE = 'SAVE'
MODEL_CONFIG = "MODEL"
MODEL_KERAS = 'KERAS'
MODEL_CLASS = 'MODEL_CLASS'
MODEL_TYPE = "TYPE"
