CONFIG_PATH = 'CONFIG_PATH'
PRECISION = 'PRECISION'

OUTPUT = 'OUTPUT'
SOURCES = 'SOURCES'
DATA_SOURCE_TYPE = 'TYPE'
INPUT = 'INPUT'
MIMES = 'MIMES'
CHARACTER = 'CHARACTER'

ENV_DIR = 'ENV_DIR'
DATA_SOURCE_INSTANCE = 'DATA_SOURCE_INSTANCE'
TYPE_MNIST = 'MNIST'

FILE_NAME_TEMPLATE_CHARACTER_PARTIAL = ':CHAR'
FILE_NAME_TEMPLATE_VERSION_PARTIAL = ':VER'
FILE_NAME_TEMPLATE = '{0}_{1}.csv'.format(
    FILE_NAME_TEMPLATE_CHARACTER_PARTIAL,
    FILE_NAME_TEMPLATE_VERSION_PARTIAL
)
